version: "3.9" 

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/data/postgres

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    user: 1000:1000
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://postgres:password@db/postgres"

volumes:
  postgres_data:
