version: "3.9" 

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
       - postgres_data:/data/postgres

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    user: 1000:1000
    env_file:
      - ./.env

volumes:
  postgres_data:
